/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chaostocosmos.io.console;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
